spring:
  main:
    lazy-initialization: true
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres?currentSchema=my-ddd
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 16379
  # 如果连接测试库，可以移回测试目录的配置文件
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: true
cache:
  caffeine:
    maximumSize: 1000
    expireAfterWriteSeconds: 300
  redis:
    timeToLiveSeconds: 600